name: WakaTime Metrics

on:
  schedule:
    - cron: '30 18 * * *'
  workflow_dispatch:

concurrency:
  group: readme-update
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  update-readme:
    name: Update WakaTime Metrics in README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          SECTION_NAME: waka
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          TIME_RANGE: last_7_days
          LANG_COUNT: 5
          SHOW_TIME: true
          SHOW_TOTAL: true
